# Generated by Django 4.1.7 on 2025-02-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
        ('tournament', '0003_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
